from __future__ import annotations

from enum import Enum


class FactionSymbol(Enum):
    """
    AEGIS
    ANCIENTS
    ASTRO
    COBALT
    CORSAIRS
    COSMIC
    CULT
    DOMINION
    ECHO
    ETHEREAL
    GALACTIC
    LORDS
    OMEGA
    QUANTUM
    SHADOW
    SOLITARY
    UNITED
    VOID

    Properties:
    default
    """

    AEGIS = 'AEGIS'
    ANCIENTS = 'ANCIENTS'
    ASTRO = 'ASTRO'
    COBALT = 'COBALT'
    CORSAIRS = 'CORSAIRS'
    COSMIC = 'COSMIC'
    CULT = 'CULT'
    DOMINION = 'DOMINION'
    ECHO = 'ECHO'
    ETHEREAL = 'ETHEREAL'
    GALACTIC = 'GALACTIC'
    LORDS = 'LORDS'
    OBSIDIAN = 'OBSIDIAN'
    OMEGA = 'OMEGA'
    QUANTUM = 'QUANTUM'
    SHADOW = 'SHADOW'
    SOLITARY = 'SOLITARY'
    UNITED = 'UNITED'
    VOID = 'VOID'


class FactionTraitSymbol(Enum):
    """
    ADAPTABLE
    AGGRESSIVE
    BOLD
    BRUTAL
    BUREAUCRATIC
    CAPITALISTIC
    CLAN
    COLLABORATIVE
    COMMERCIAL
    COOPERATIVE
    CURIOUS
    DARING
    DEFENSIVE
    DEXTEROUS
    DISTRUSTFUL
    DIVERSE
    DOMINANT
    DOMINION
    ENTREPRENEURIAL
    ESTABLISHED
    EXILES
    EXPLORATORY
    FLEETING
    FLEXIBLE
    FORSAKEN
    FRAGMENTED
    FREE_MARKETS
    FRINGE
    GUILD
    IMPERIALISTIC
    INDEPENDENT
    INDUSTRIOUS
    INESCAPABLE
    INNOVATIVE
    INTELLIGENT
    ISOLATED
    LOCALIZED
    MILITARISTIC
    NOTABLE
    PEACEFUL
    PIRATES
    PROGRESSIVE
    PROUD
    RAIDERS
    REBELLIOUS
    RESEARCH_FOCUSED
    RESOURCEFUL
    SCAVENGERS
    SECRETIVE
    SELF_INTERESTED
    SELF_SUFFICIENT
    SMUGGLERS
    STRATEGIC
    TECHNOLOGICALLY_ADVANCED
    TREASURE_HUNTERS
    UNITED
    UNPREDICTABLE
    VISIONARY
    WELCOMING
    """

    ADAPTABLE = 'ADAPTABLE'
    AGGRESSIVE = 'AGGRESSIVE'
    BOLD = 'BOLD'
    BRUTAL = 'BRUTAL'
    BUREAUCRATIC = 'BUREAUCRATIC'
    CAPITALISTIC = 'CAPITALISTIC'
    CLAN = 'CLAN'
    COLLABORATIVE = 'COLLABORATIVE'
    COMMERCIAL = 'COMMERCIAL'
    COOPERATIVE = 'COOPERATIVE'
    CURIOUS = 'CURIOUS'
    DARING = 'DARING'
    DEFENSIVE = 'DEFENSIVE'
    DEXTEROUS = 'DEXTEROUS'
    DISTRUSTFUL = 'DISTRUSTFUL'
    DIVERSE = 'DIVERSE'
    DOMINANT = 'DOMINANT'
    DOMINION = 'DOMINION'
    ENTREPRENEURIAL = 'ENTREPRENEURIAL'
    ESTABLISHED = 'ESTABLISHED'
    EXILES = 'EXILES'
    EXPLORATORY = 'EXPLORATORY'
    FLEETING = 'FLEETING'
    FLEXIBLE = 'FLEXIBLE'
    FORSAKEN = 'FORSAKEN'
    FRAGMENTED = 'FRAGMENTED'
    FREE_MARKETS = 'FREE_MARKETS'
    FRINGE = 'FRINGE'
    GUILD = 'GUILD'
    IMPERIALISTIC = 'IMPERIALISTIC'
    INDEPENDENT = 'INDEPENDENT'
    INDUSTRIOUS = 'INDUSTRIOUS'
    INESCAPABLE = 'INESCAPABLE'
    INNOVATIVE = 'INNOVATIVE'
    INTELLIGENT = 'INTELLIGENT'
    ISOLATED = 'ISOLATED'
    LOCALIZED = 'LOCALIZED'
    MILITARISTIC = 'MILITARISTIC'
    NOTABLE = 'NOTABLE'
    PEACEFUL = 'PEACEFUL'
    PIRATES = 'PIRATES'
    PROGRESSIVE = 'PROGRESSIVE'
    PROUD = 'PROUD'
    RAIDERS = 'RAIDERS'
    REBELLIOUS = 'REBELLIOUS'
    RESEARCH_FOCUSED = 'RESEARCH_FOCUSED'
    RESOURCEFUL = 'RESOURCEFUL'
    SCAVENGERS = 'SCAVENGERS'
    SECRETIVE = 'SECRETIVE'
    SELF_INTERESTED = 'SELF_INTERESTED'
    SELF_SUFFICIENT = 'SELF_SUFFICIENT'
    SMUGGLERS = 'SMUGGLERS'
    STRATEGIC = 'STRATEGIC'
    TECHNOLOGICALLY_ADVANCED = 'TECHNOLOGICALLY_ADVANCED'
    TREASURE_HUNTERS = 'TREASURE_HUNTERS'
    UNITED = 'UNITED'
    UNPREDICTABLE = 'UNPREDICTABLE'
    VISIONARY = 'VISIONARY'
    WELCOMING = 'WELCOMING'
