from enum import Enum, auto


class WaypointModifierSymbol(Enum):
    STRIPPED = auto()
    UNSTABLE = auto()
    RADIATION_LEAK = auto()
    CRITICAL_LIMIT = auto()
    CIVIL_UNREST = auto()


class WaypointTraitSymbol(Enum):
    UNCHARTED = auto()
    UNDER_CONSTRUCTION = auto()
    MARKETPLACE = auto()
    SHIPYARD = auto()
    OUTPOST = auto()
    SCATTERED_SETTLEMENTS = auto()
    SPRAWLING_CITIES = auto()
    MEGA_STRUCTURES = auto()
    PIRATE_BASE = auto()
    OVERCROWDED = auto()
    HIGH_TECH = auto()
    CORRUPT = auto()
    BUREAUCRATIC = auto()
    TRADING_HUB = auto()
    INDUSTRIAL = auto()
    BLACK_MARKET = auto()
    RESEARCH_FACILITY = auto()
    MILITARY_BASE = auto()
    SURVEILLANCE_OUTPOST = auto()
    EXPLORATION_OUTPOST = auto()
    MINERAL_DEPOSITS = auto()
    COMMON_METAL_DEPOSITS = auto()
    PRECIOUS_METAL_DEPOSITS = auto()
    RARE_METAL_DEPOSITS = auto()
    METHANE_POOLS = auto()
    ICE_CRYSTALS = auto()
    EXPLOSIVE_GASES = auto()
    STRONG_MAGNETOSPHERE = auto()
    VIBRANT_AURORAS = auto()
    SALT_FLATS = auto()
    CANYONS = auto()
    PERPETUAL_DAYLIGHT = auto()
    PERPETUAL_OVERCAST = auto()
    DRY_SEABEDS = auto()
    MAGMA_SEAS = auto()
    SUPERVOLCANOES = auto()
    ASH_CLOUDS = auto()
    VAST_RUINS = auto()
    MUTATED_FLORA = auto()
    TERRAFORMED = auto()
    EXTREME_TEMPERATURES = auto()
    EXTREME_PRESSURE = auto()
    DIVERSE_LIFE = auto()
    SCARCE_LIFE = auto()
    FOSSILS = auto()
    WEAK_GRAVITY = auto()
    STRONG_GRAVITY = auto()
    CRUSHING_GRAVITY = auto()
    TOXIC_ATMOSPHERE = auto()
    CORROSIVE_ATMOSPHERE = auto()
    BREATHABLE_ATMOSPHERE = auto()
    THIN_ATMOSPHERE = auto()
    JOVIAN = auto()
    ROCKY = auto()
    VOLCANIC = auto()
    FROZEN = auto()
    SWAMP = auto()
    BARREN = auto()
    TEMPERATE = auto()
    JUNGLE = auto()
    OCEAN = auto()
    RADIOACTIVE = auto()
    MICRO_GRAVITY_ANOMALIES = auto()
    DEBRIS_CLUSTER = auto()
    DEEP_CRATERS = auto()
    SHALLOW_CRATERS = auto()
    UNSTABLE_COMPOSITION = auto()
    HOLLOWED_INTERIOR = auto()
    STRIPPED = auto()


class WaypointType(Enum):
    PLANET = auto()
    GAS_GIANT = auto()
    MOON = auto()
    ORBITAL_STATION = auto()
    JUMP_GATE = auto()
    ASTEROID_FIELD = auto()
    ASTEROID = auto()
    ENGINEERED_ASTEROID = auto()
    ASTEROID_BASE = auto()
    NEBULA = auto()
    DEBRIS_FIELD = auto()
    GRAVITY_WELL = auto()
    ARTIFICIAL_GRAVITY_WELL = auto()
    FUEL_STATION = auto()

