from enum import Enum, auto


class FactionSymbol(Enum):
    COSMIC = auto()
    VOID = auto()
    GALACTIC = auto()
    QUANTUM = auto()
    DOMINION = auto()
    ASTRO = auto()
    CORSAIRS = auto()
    AEGIS = auto()
    UNITED = auto()
    SOLITARY = auto()
    COBALT = auto()
    OMEGA = auto()
    ECHO = auto()
    LORDS = auto()
    CULT = auto()
    ANCIENTS = auto()
    SHADOW = auto()
    ETHEREAL = auto()


class FactionTraitSymbol(Enum):
    BUREAUCRATIC = auto()
    SECRETIVE = auto()
    CAPITALISTIC = auto()
    INDUSTRIOUS = auto()
    PEACEFUL = auto()
    DISTRUSTFUL = auto()
    WELCOMING = auto()
    SMUGGLERS = auto()
    SCAVENGERS = auto()
    REBELLIOUS = auto()
    EXILES = auto()
    PIRATES = auto()
    RAIDERS = auto()
    CLAN = auto()
    GUILD = auto()
    DOMINION = auto()
    FRINGE = auto()
    FORSAKEN = auto()
    ISOLATED = auto()
    LOCALIZED = auto()
    ESTABLISHED = auto()
    NOTABLE = auto()
    DOMINANT = auto()
    INESCAPABLE = auto()
    INNOVATIVE = auto()
    BOLD = auto()
    VISIONARY = auto()
    CURIOUS = auto()
    DARING = auto()
    EXPLORATORY = auto()
    RESOURCEFUL = auto()
    FLEXIBLE = auto()
    COOPERATIVE = auto()
    UNITED = auto()
    STRATEGIC = auto()
    INTELLIGENT = auto()
    RESEARCH_FOCUSED = auto()
    COLLABORATIVE = auto()
    PROGRESSIVE = auto()
    MILITARISTIC = auto()
    TECHNOLOGICALLY_ADVANCED = auto()
    AGGRESSIVE = auto()
    IMPERIALISTIC = auto()
    TREASURE_HUNTERS = auto()
    DEXTEROUS = auto()
    UNPREDICTABLE = auto()
    BRUTAL = auto()
    FLEETING = auto()
    ADAPTABLE = auto()
    SELF_SUFFICIENT = auto()
    DEFENSIVE = auto()
    PROUD = auto()
    DIVERSE = auto()
    INDEPENDENT = auto()
    SELF_INTERESTED = auto()
    FRAGMENTED = auto()
    COMMERCIAL = auto()
    FREE_MARKETS = auto()
    ENTREPRENEURIAL = auto()


class SystemType(Enum):
    NEUTRON_STAR = auto()
    RED_STAR = auto()
    ORANGE_STAR = auto()
    BLUE_STAR = auto()
    YOUNG_STAR = auto()
    WHITE_DWARF = auto()
    BLACK_HOLE = auto()
    HYPERGIANT = auto()
    NEBULA = auto()
    UNSTABLE = auto()


class WaypointType(Enum):
    PLANET = auto()
    GAS_GIANT = auto()
    MOON = auto()
    ORBITAL_STATION = auto()
    JUMP_GATE = auto()
    ASTEROID_FIELD = auto()
    ASTEROID = auto()
    ENGINEERED_ASTEROID = auto()
    ASTEROID_BASE = auto()
    NEBULA = auto()
    DEBRIS_FIELD = auto()
    GRAVITY_WELL = auto()
    ARTIFICIAL_GRAVITY_WELL = auto()
    FUEL_STATION = auto()


class WaypointTraitSymbol(Enum):
    UNCHARTED = auto()
    UNDER_CONSTRUCTION = auto()
    MARKETPLACE = auto()
    SHIPYARD = auto()
    OUTPOST = auto()
    SCATTERED_SETTLEMENTS = auto()
    SPRAWLING_CITIES = auto()
    MEGA_STRUCTURES = auto()
    PIRATE_BASE = auto()
    OVERCROWDED = auto()
    HIGH_TECH = auto()
    CORRUPT = auto()
    BUREAUCRATIC = auto()
    TRADING_HUB = auto()
    INDUSTRIAL = auto()
    BLACK_MARKET = auto()
    RESEARCH_FACILITY = auto()
    MILITARY_BASE = auto()
    SURVEILLANCE_OUTPOST = auto()
    EXPLORATION_OUTPOST = auto()
    MINERAL_DEPOSITS = auto()
    COMMON_METAL_DEPOSITS = auto()
    PRECIOUS_METAL_DEPOSITS = auto()
    RARE_METAL_DEPOSITS = auto()
    METHANE_POOLS = auto()
    ICE_CRYSTALS = auto()
    EXPLOSIVE_GASES = auto()
    STRONG_MAGNETOSPHERE = auto()
    VIBRANT_AURORAS = auto()
    SALT_FLATS = auto()
    CANYONS = auto()
    PERPETUAL_DAYLIGHT = auto()
    PERPETUAL_OVERCAST = auto()
    DRY_SEABEDS = auto()
    MAGMA_SEAS = auto()
    SUPERVOLCANOES = auto()
    ASH_CLOUDS = auto()
    VAST_RUINS = auto()
    MUTATED_FLORA = auto()
    TERRAFORMED = auto()
    EXTREME_TEMPERATURES = auto()
    EXTREME_PRESSURE = auto()
    DIVERSE_LIFE = auto()
    SCARCE_LIFE = auto()
    FOSSILS = auto()
    WEAK_GRAVITY = auto()
    STRONG_GRAVITY = auto()
    CRUSHING_GRAVITY = auto()
    TOXIC_ATMOSPHERE = auto()
    CORROSIVE_ATMOSPHERE = auto()
    BREATHABLE_ATMOSPHERE = auto()
    THIN_ATMOSPHERE = auto()
    JOVIAN = auto()
    ROCKY = auto()
    VOLCANIC = auto()
    FROZEN = auto()
    SWAMP = auto()
    BARREN = auto()
    TEMPERATE = auto()
    JUNGLE = auto()
    OCEAN = auto()
    RADIOACTIVE = auto()
    MICRO_GRAVITY_ANOMALIES = auto()
    DEBRIS_CLUSTER = auto()
    DEEP_CRATERS = auto()
    SHALLOW_CRATERS = auto()
    UNSTABLE_COMPOSITION = auto()
    HOLLOWED_INTERIOR = auto()
    STRIPPED = auto()


class WaypointModifierSymbol(Enum):
    STRIPPED = auto()
    UNSTABLE = auto()
    RADIATION_LEAK = auto()
    CRITICAL_LIMIT = auto()
    CIVIL_UNREST = auto()


# Also used by ShipCargoItem, TradeGood
class TradeSymbol(Enum):
    PRECIOUS_STONES = auto()
    QUARTZ_SAND = auto()
    SILICON_CRYSTALS = auto()
    AMMONIA_ICE = auto()
    LIQUID_HYDROGEN = auto()
    LIQUID_NITROGEN = auto()
    ICE_WATER = auto()
    EXOTIC_MATTER = auto()
    ADVANCED_CIRCUITRY = auto()
    GRAVITON_EMITTERS = auto()
    IRON = auto()
    IRON_ORE = auto()
    COPPER = auto()
    COPPER_ORE = auto()
    ALUMINUM = auto()
    ALUMINUM_ORE = auto()
    SILVER = auto()
    SILVER_ORE = auto()
    GOLD = auto()
    GOLD_ORE = auto()
    PLATINUM = auto()
    PLATINUM_ORE = auto()
    DIAMONDS = auto()
    URANITE = auto()
    URANITE_ORE = auto()
    MERITIUM = auto()
    MERITIUM_ORE = auto()
    HYDROCARBON = auto()
    ANTIMATTER = auto()
    FAB_MATS = auto()
    FERTILIZERS = auto()
    FABRICS = auto()
    FOOD = auto()
    JEWELRY = auto()
    MACHINERY = auto()
    FIREARMS = auto()
    ASSAULT_RIFLES = auto()
    MILITARY_EQUIPMENT = auto()
    EXPLOSIVES = auto()
    LAB_INSTRUMENTS = auto()
    AMMUNITION = auto()
    ELECTRONICS = auto()
    SHIP_PLATING = auto()
    SHIP_PARTS = auto()
    EQUIPMENT = auto()
    FUEL = auto()
    MEDICINE = auto()
    DRUGS = auto()
    CLOTHING = auto()
    MICROPROCESSORS = auto()
    PLASTICS = auto()
    POLYNUCLEOTIDES = auto()
    BIOCOMPOSITES = auto()
    QUANTUM_STABILIZERS = auto()
    NANOBOTS = auto()
    AI_MAINFRAMES = auto()
    QUANTUM_DRIVES = auto()
    ROBOTIC_DRONES = auto()
    CYBER_IMPLANTS = auto()
    GENE_THERAPEUTICS = auto()
    NEURAL_CHIPS = auto()
    MOOD_REGULATORS = auto()
    VIRAL_AGENTS = auto()
    MICRO_FUSION_GENERATORS = auto()
    SUPERGRAINS = auto()
    LASER_RIFLES = auto()
    HOLOGRAPHICS = auto()
    SHIP_SALVAGE = auto()
    RELIC_TECH = auto()
    NOVEL_LIFEFORMS = auto()
    BOTANICAL_SPECIMENS = auto()
    CULTURAL_ARTIFACTS = auto()
    FRAME_PROBE = auto()
    FRAME_DRONE = auto()
    FRAME_INTERCEPTOR = auto()
    FRAME_RACER = auto()
    FRAME_FIGHTER = auto()
    FRAME_FRIGATE = auto()
    FRAME_SHUTTLE = auto()
    FRAME_EXPLORER = auto()
    FRAME_MINER = auto()
    FRAME_LIGHT_FREIGHTER = auto()
    FRAME_HEAVY_FREIGHTER = auto()
    FRAME_TRANSPORT = auto()
    FRAME_DESTROYER = auto()
    FRAME_CRUISER = auto()
    FRAME_CARRIER = auto()
    FRAME_BULK_FREIGHTER = auto()
    REACTOR_SOLAR_I = auto()
    REACTOR_FUSION_I = auto()
    REACTOR_FISSION_I = auto()
    REACTOR_CHEMICAL_I = auto()
    REACTOR_ANTIMATTER_I = auto()
    ENGINE_IMPULSE_DRIVE_I = auto()
    ENGINE_ION_DRIVE_I = auto()
    ENGINE_ION_DRIVE_II = auto()
    ENGINE_HYPER_DRIVE_I = auto()
    MODULE_MINERAL_PROCESSOR_I = auto()
    MODULE_GAS_PROCESSOR_I = auto()
    MODULE_CARGO_HOLD_I = auto()
    MODULE_CARGO_HOLD_II = auto()
    MODULE_CARGO_HOLD_III = auto()
    MODULE_CREW_QUARTERS_I = auto()
    MODULE_ENVOY_QUARTERS_I = auto()
    MODULE_PASSENGER_CABIN_I = auto()
    MODULE_MICRO_REFINERY_I = auto()
    MODULE_SCIENCE_LAB_I = auto()
    MODULE_JUMP_DRIVE_I = auto()
    MODULE_JUMP_DRIVE_II = auto()
    MODULE_JUMP_DRIVE_III = auto()
    MODULE_WARP_DRIVE_I = auto()
    MODULE_WARP_DRIVE_II = auto()
    MODULE_WARP_DRIVE_III = auto()
    MODULE_SHIELD_GENERATOR_I = auto()
    MODULE_SHIELD_GENERATOR_II = auto()
    MODULE_ORE_REFINERY_I = auto()
    MODULE_FUEL_REFINERY_I = auto()
    MOUNT_GAS_SIPHON_I = auto()
    MOUNT_GAS_SIPHON_II = auto()
    MOUNT_GAS_SIPHON_III = auto()
    MOUNT_SURVEYOR_I = auto()
    MOUNT_SURVEYOR_II = auto()
    MOUNT_SURVEYOR_III = auto()
    MOUNT_SENSOR_ARRAY_I = auto()
    MOUNT_SENSOR_ARRAY_II = auto()
    MOUNT_SENSOR_ARRAY_III = auto()
    MOUNT_MINING_LASER_I = auto()
    MOUNT_MINING_LASER_II = auto()
    MOUNT_MINING_LASER_III = auto()
    MOUNT_LASER_CANNON_I = auto()
    MOUNT_MISSILE_LAUNCHER_I = auto()
    MOUNT_TURRET_I = auto()
    SHIP_PROBE = auto()
    SHIP_MINING_DRONE = auto()
    SHIP_SIPHON_DRONE = auto()
    SHIP_INTERCEPTOR = auto()
    SHIP_LIGHT_HAULER = auto()
    SHIP_COMMAND_FRIGATE = auto()
    SHIP_EXPLORER = auto()
    SHIP_HEAVY_FREIGHTER = auto()
    SHIP_LIGHT_SHUTTLE = auto()
    SHIP_ORE_HOUND = auto()
    SHIP_REFINING_FREIGHTER = auto()
    SHIP_SURVEYOR = auto()
    SHIP_BULK_FREIGHTER = auto()


class MarketTransactionType(Enum):
    PURCHASE = auto()
    SELL = auto()


class MarketTradeGoodType(Enum):
    EXPORT = auto()
    IMPORT = auto()
    EXCHANGE = auto()


class SupplyLevel(Enum):
    SCARCE = auto()
    LIMITED = auto()
    MODERATE = auto()
    HIGH = auto()
    ABUNDANT = auto()


class ActivityLevel(Enum):
    WEAK = auto()
    GROWING = auto()
    STRONG = auto()
    RESTRICTED = auto()


class ShipType(Enum):
    SHIP_PROBE = auto()
    SHIP_MINING_DRONE = auto()
    SHIP_SIPHON_DRONE = auto()
    SHIP_INTERCEPTOR = auto()
    SHIP_LIGHT_HAULER = auto()
    SHIP_COMMAND_FRIGATE = auto()
    SHIP_EXPLORER = auto()
    SHIP_HEAVY_FREIGHTER = auto()
    SHIP_LIGHT_SHUTTLE = auto()
    SHIP_ORE_HOUND = auto()
    SHIP_REFINING_FREIGHTER = auto()
    SHIP_SURVEYOR = auto()
    SHIP_BULK_FREIGHTER = auto()


class ShipFrames(Enum):
    FRAME_PROBE = auto()
    FRAME_DRONE = auto()
    FRAME_INTERCEPTOR = auto()
    FRAME_RACER = auto()
    FRAME_FIGHTER = auto()
    FRAME_FRIGATE = auto()
    FRAME_SHUTTLE = auto()
    FRAME_EXPLORER = auto()
    FRAME_MINER = auto()
    FRAME_LIGHT_FREIGHTER = auto()
    FRAME_HEAVY_FREIGHTER = auto()
    FRAME_TRANSPORT = auto()
    FRAME_DESTROYER = auto()
    FRAME_CRUISER = auto()
    FRAME_CARRIER = auto()
    FRAME_BULK_FREIGHTER = auto()


class ShipReactors(Enum):
    REACTOR_SOLAR_I = auto()
    REACTOR_FUSION_I = auto()
    REACTOR_FISSION_I = auto()
    REACTOR_CHEMICAL_I = auto()
    REACTOR_ANTIMATTER_I = auto()


class ShipEngines(Enum):
    ENGINE_IMPULSE_DRIVE_I = auto()
    ENGINE_ION_DRIVE_I = auto()
    ENGINE_ION_DRIVE_II = auto()
    ENGINE_HYPER_DRIVE_I = auto()


class ShipModules(Enum):
    MODULE_MINERAL_PROCESSOR_I = auto()
    MODULE_GAS_PROCESSOR_I = auto()
    MODULE_CARGO_HOLD_I = auto()
    MODULE_CARGO_HOLD_II = auto()
    MODULE_CARGO_HOLD_III = auto()
    MODULE_CREW_QUARTERS_I = auto()
    MODULE_ENVOY_QUARTERS_I = auto()
    MODULE_PASSENGER_CABIN_I = auto()
    MODULE_MICRO_REFINERY_I = auto()
    MODULE_ORE_REFINERY_I = auto()
    MODULE_FUEL_REFINERY_I = auto()
    MODULE_SCIENCE_LAB_I = auto()
    MODULE_JUMP_DRIVE_I = auto()
    MODULE_JUMP_DRIVE_II = auto()
    MODULE_JUMP_DRIVE_III = auto()
    MODULE_WARP_DRIVE_I = auto()
    MODULE_WARP_DRIVE_II = auto()
    MODULE_WARP_DRIVE_III = auto()
    MODULE_SHIELD_GENERATOR_I = auto()
    MODULE_SHIELD_GENERATOR_II = auto()


class ShipMounts(Enum):
    MOUNT_GAS_SIPHON_I = auto()
    MOUNT_GAS_SIPHON_II = auto()
    MOUNT_GAS_SIPHON_III = auto()
    MOUNT_SURVEYOR_I = auto()
    MOUNT_SURVEYOR_II = auto()
    MOUNT_SURVEYOR_III = auto()
    MOUNT_SENSOR_ARRAY_I = auto()
    MOUNT_SENSOR_ARRAY_II = auto()
    MOUNT_SENSOR_ARRAY_III = auto()
    MOUNT_MINING_LASER_I = auto()
    MOUNT_MINING_LASER_II = auto()
    MOUNT_MINING_LASER_III = auto()
    MOUNT_LASER_CANNON_I = auto()
    MOUNT_MISSILE_LAUNCHER_I = auto()
    MOUNT_TURRET_I = auto()


class ShipMountDeposits(Enum):
    QUARTZ_SAND = auto()
    SILICON_CRYSTALS = auto()
    PRECIOUS_STONES = auto()
    ICE_WATER = auto()
    AMMONIA_ICE = auto()
    IRON_ORE = auto()
    COPPER_ORE = auto()
    SILVER_ORE = auto()
    ALUMINUM_ORE = auto()
    GOLD_ORE = auto()
    PLATINUM_ORE = auto()
    DIAMONDS = auto()
    URANITE_ORE = auto()
    MERITIUM_ORE = auto()


class ContractType(Enum):
    PROCUREMENT = auto()
    TRANSPORT = auto()
    SHUTTLE = auto()


class ShipRole(Enum):
    FABRICATOR = auto()
    HARVESTER = auto()
    HAULER = auto()
    INTERCEPTOR = auto()
    EXCAVATOR = auto()
    TRANSPORT = auto()
    REPAIR = auto()
    SURVEYOR = auto()
    COMMAND = auto()
    CARRIER = auto()
    PATROL = auto()
    SATELLITE = auto()
    EXPLORER = auto()
    REFINERY = auto()


class ShipNavStatus(Enum):
    IN_TRANSIT = auto()
    IN_ORBIT = auto()
    DOCKED = auto()


class ShipNavFlightMode(Enum):
    DRIFT = auto()
    STEALTH = auto()
    CRUISE = auto()
    BURN = auto()


class ShipCrewRotation(Enum):
    STRICT = auto()
    RELAXED = auto()


class ShipConditionEvent(Enum):
    REACTOR_OVERLOAD = auto()
    ENERGY_SPIKE_FROM_MINERAL = auto()
    SOLAR_FLARE_INTERFERENCE = auto()
    COOLANT_LEAK = auto()
    POWER_DISTRIBUTION_FLUCTUATION = auto()
    MAGNETIC_FIELD_DISRUPTION = auto()
    HULL_MICROMETEORITE_STRIKES = auto()
    STRUCTURAL_STRESS_FRACTURES = auto()
    CORROSIVE_MINERAL_CONTAMINATION = auto()
    THERMAL_EXPANSION_MISMATCH = auto()
    VIBRATION_DAMAGE_FROM_DRILLING = auto()
    ELECTROMAGNETIC_FIELD_INTERFERENCE = auto()
    IMPACT_WITH_EXTRACTED_DEBRIS = auto()
    FUEL_EFFICIENCY_DEGRADATION = auto()
    COOLANT_SYSTEM_AGEING = auto()
    DUST_MICROABRASIONS = auto()
    THRUSTER_NOZZLE_WEAR = auto()
    EXHAUST_PORT_CLOGGING = auto()
    BEARING_LUBRICATION_FADE = auto()
    SENSOR_CALIBRATION_DRIFT = auto()
    HULL_MICROMETEORITE_DAMAGE = auto()
    SPACE_DEBRIS_COLLISION = auto()
    THERMAL_STRESS = auto()
    VIBRATION_OVERLOAD = auto()
    PRESSURE_DIFFERENTIAL_STRESS = auto()
    ELECTROMAGNETIC_SURGE_EFFECTS = auto()
    ATMOSPHERIC_ENTRY_HEAT = auto()


class ShipComponent(Enum):
    FRAME = auto()
    REACTOR = auto()
    ENGINE = auto()


class SurveySize(Enum):
    SMALL = auto()
    MODERATE = auto()
    LARGE = auto()

